# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  VITE_API_BASE = "https://simple-marketplace-api-production.up.railway.app/api"
  VITE_DEFAULT_USER_ID = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
